CREATE DATABASE DapperDB

USE DapperDB

BEGIN;
CREATE TABLE Person (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(255),
    Address VARCHAR(255),
    City VARCHAR(255) 
);

CREATE TABLE PetType (
  Id INT PRIMARY KEY AUTO_INCREMENT,
  Name VARCHAR(200) NOT NULL
);

CREATE TABLE Pet (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    PersonId INT,
    Name VARCHAR(255) NOT NULL,
    PetTypeId INT,
    Age INT,
    Color VARCHAR(255) NOT NULL,
    FOREIGN KEY (PersonId) REFERENCES Person (Id),
    FOREIGN KEY (PetTypeId) REFERENCES PetType (Id)
);
COMMIT


